name: Make Script Executable

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Change file permissions
      run: |
        chmod +x path/to/your/script.sh
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add 0x16-api_advanced/0-subs.py
        git commit -m "Make script.sh executable"
        git push
